language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g sequelize-cli
  - sequelize db:migrate --config server/db/config.json --migrations-path server/db/migrations --models-path server/db/models --env test
